sites = {
    "google": "https://google.com",
    "youtube": "https://youtube.com",
    "github": "https://github.com",
    "chatgpt": "https://chatgpt.com",
    "wikipedia": "https://wikipedia.org",
    "instagram": "https://instagram.com",
    "facebook": "https://facebook.com",
    "twitter": "https://x.com",
    "reddit": "https://reddit.com",
    "linkedin": "https://linkedin.com",
    "discord": "https://discord.com",
    "gmail": "https://gmail.com",
    "outlook": "https://outlook.com",
    "amazon": "https://amazon.in",
    "flipkart": "https://flipkart.com",
    "myntra": "https://myntra.com",
    "netflix": "https://netflix.com",
    "spotify": "https://spotify.com",
    "hotstar": "https://hotstar.com",
    "prime video": "https://primevideo.com",
    "leetcode": "https://leetcode.com",
    "geeksforgeeks": "https://geeksforgeeks.org",
    "hackerrank": "https://hackerrank.com",
    "stackoverflow": "https://stackoverflow.com",
    "w3schools": "https://w3schools.com",
    "coursera": "https://coursera.org",
    "udemy": "https://udemy.com",
    "drive": "https://drive.google.com",
    "maps": "https://maps.google.com",
    "whatsapp": "https://web.whatsapp.com"
}